services:
  web:
    build:
      context: .
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    env_file:
      - .env
    stop_signal: SIGINT
    ports:
      - '9091:9091'
    volumes:
      - ./study:/study
      - .:/app